name: CI_build

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest
    env:
      Projectname: NMD
    strategy:
      fail-fast: false
      matrix:
        build_platform: [x64, Win32, ARM64]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v7

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v3

    - name: Setup NuGet
      uses: nuget/setup-nuget@v4

    - name: Nuget restore dependencies
      run: nuget restore ${{ env.Projectname }}.sln

    - name: MSBuild of plugin dll Debug
      working-directory: .\
      run: |
           msbuild ${{ env.Projectname }}.vcxproj /m /p:configuration=Debug /p:platform="${{ matrix.build_platform }}"

    - name: MSBuild of plugin dll Release
      working-directory: .\
      run: |
           msbuild ${{ env.Projectname }}.vcxproj /m /p:configuration=Release /p:platform="${{ matrix.build_platform }}"

    - uses: olegtarasov/get-tag@v2.1.4
      id: tagName

    - name: zip artifacts for Release ${{ matrix.build_platform }}
      run: |
           7z a ${{ env.Projectname }}_${{ steps.tagName.outputs.tag }}_${{ matrix.build_platform }}.zip .\${{ matrix.build_platform }}\Release\${{ env.Projectname }}.dll

    - name: Archive artifacts for Release ${{ matrix.build_platform }}
      uses: actions/upload-artifact@v7
      with:
        name: ${{ env.Projectname }}_${{ steps.tagName.outputs.tag }}_${{ matrix.build_platform }}.zip
        path: ${{ env.Projectname }}_${{ steps.tagName.outputs.tag }}_${{ matrix.build_platform }}.zip

    - name: Create release on tagging
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ env.Projectname }}_${{ steps.tagName.outputs.tag }}_${{ matrix.build_platform }}.zip